version: '2'
services:
    gogs_server:
        image: gogs/gogs
        ports:
            - "3000:3000"
            - "10022:22"
        volumes:
            - gogs_server_data:/data
        networks:
          - gogs_network
    gogs_db:
        image: mysql
        volumes:
            - gogs_db_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=gogs
        networks:
          gogs_network:
            aliases:
              - mysql

volumes:
  gogs_server_data:
    driver: local
  gogs_db_data:
    driver: local

networks:
  gogs_network:
